<?php
/**
 * Yireo BingTranslate for Magento
 *
 * @package     Yireo_BingTranslate
 * @author      Yireo (http://www.yireo.com/)
 * @copyright   Copyright (c) 2015 Yireo (http://www.yireo.com/)
 * @license     Open Software License
 */
?>
<script type="text/javascript">
    YireoBingTranslate.ajaxEntityBaseUrl = '<?= $this->getAjaxEntityBaseUrl(); ?>';
    YireoBingTranslate.ajaxTextBaseUrl = '<?= $this->getAjaxTextBaseUrl(); ?>';
</script>